version: "3.8"

services:
    #   kling-server:
    #     build: ./apps/api-rest
    #     container_name: kling-server
    #     volumes:
    #       - /usr/src/app/node_modules
    #     ports:
    #       - 3100:3100
    #     networks:
    #       - webnet
    #     environment:
    #       DB_TYPE: postgres
    #       DB_HOST: postgres
    #       DB_PORT: 5432
    #       DB_USERNAME: postgres
    #       DB_PASSWORD: postgres
    #       DB_DATABASE: KlingDb
    #       NATS_URL: nats://nats-streaming:4222
    #     volumes:
    #       - .:/usr/src/app
    #       - /usr/src/app/node_modules
    #     depends_on:
    #       - postgres
    #       - nats

    postgres:
        container_name: postgres
        image: postgres:12
        networks:
            - webnet
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: KlingDb
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    nats:
        container_name: nats-streaming
        image: nats-streaming
        ports:
            - 4222:4222
            - 8222:8222
        networks:
            - webnet

networks:
    webnet:
volumes:
    pgdata:
