/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoundingBehavior } from './roundingBehavior';


export interface AdmissionRuleDto { 
    type: AdmissionRuleDto.TypeEnum;
    assignmentType: AdmissionRuleDto.AssignmentTypeEnum;
    requiredPercent: number;
    achievedPercentRounding: RoundingBehavior;
}
export namespace AdmissionRuleDto {
    export type TypeEnum = 'INDIVIDUAL_PERCENT_WITH_ALLOWED_FAILURES' | 'REQUIRED_PERCENT_OVERALL';
    export const TypeEnum = {
        IndividualPercentWithAllowedFailures: 'INDIVIDUAL_PERCENT_WITH_ALLOWED_FAILURES' as TypeEnum,
        RequiredPercentOverall: 'REQUIRED_PERCENT_OVERALL' as TypeEnum
    };
    export type AssignmentTypeEnum = 'HOMEWORK' | 'TESTAT' | 'SEMINAR' | 'PROJECT' | 'OTHER';
    export const AssignmentTypeEnum = {
        Homework: 'HOMEWORK' as AssignmentTypeEnum,
        Testat: 'TESTAT' as AssignmentTypeEnum,
        Seminar: 'SEMINAR' as AssignmentTypeEnum,
        Project: 'PROJECT' as AssignmentTypeEnum,
        Other: 'OTHER' as AssignmentTypeEnum
    };
}


