/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    event: NotificationDto.EventEnum;
    courseId: string;
    assignmentId?: string;
    groupId?: string;
    userId?: string;
    payload?: object;
}
export namespace NotificationDto {
    export type EventEnum = 'COURSE_JOINED' | 'ASSIGNMENT_CREATED' | 'ASSIGNMENT_REMOVED' | 'ASSIGNMENT_STATE_CHANGED' | 'GROUP_REGISTERED' | 'GROUP_UNREGISTERED' | 'USER_REGISTERED' | 'USER_UNREGISTERED' | 'USER_JOINED_GROUP' | 'USER_LEFT_GROUP' | 'REGISTRATIONS_CREATED' | 'REGISTRATIONS_REMOVED';
    export const EventEnum = {
        CourseJoined: 'COURSE_JOINED' as EventEnum,
        AssignmentCreated: 'ASSIGNMENT_CREATED' as EventEnum,
        AssignmentRemoved: 'ASSIGNMENT_REMOVED' as EventEnum,
        AssignmentStateChanged: 'ASSIGNMENT_STATE_CHANGED' as EventEnum,
        GroupRegistered: 'GROUP_REGISTERED' as EventEnum,
        GroupUnregistered: 'GROUP_UNREGISTERED' as EventEnum,
        UserRegistered: 'USER_REGISTERED' as EventEnum,
        UserUnregistered: 'USER_UNREGISTERED' as EventEnum,
        UserJoinedGroup: 'USER_JOINED_GROUP' as EventEnum,
        UserLeftGroup: 'USER_LEFT_GROUP' as EventEnum,
        RegistrationsCreated: 'REGISTRATIONS_CREATED' as EventEnum,
        RegistrationsRemoved: 'REGISTRATIONS_REMOVED' as EventEnum
    };
}


