/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RuleCheckResult { 
    passed: boolean;
    achievedPoints: number;
    achievedPercent: number;
    comment?: string;
    _rule: RuleCheckResult.RuleEnum;
    _assignmentType: RuleCheckResult.AssignmentTypeEnum;
}
export namespace RuleCheckResult {
    export type RuleEnum = 'INDIVIDUAL_PERCENT_WITH_ALLOWED_FAILURES' | 'REQUIRED_PERCENT_OVERALL';
    export const RuleEnum = {
        IndividualPercentWithAllowedFailures: 'INDIVIDUAL_PERCENT_WITH_ALLOWED_FAILURES' as RuleEnum,
        RequiredPercentOverall: 'REQUIRED_PERCENT_OVERALL' as RuleEnum
    };
    export type AssignmentTypeEnum = 'HOMEWORK' | 'TESTAT' | 'SEMINAR' | 'PROJECT' | 'OTHER';
    export const AssignmentTypeEnum = {
        Homework: 'HOMEWORK' as AssignmentTypeEnum,
        Testat: 'TESTAT' as AssignmentTypeEnum,
        Seminar: 'SEMINAR' as AssignmentTypeEnum,
        Project: 'PROJECT' as AssignmentTypeEnum,
        Other: 'OTHER' as AssignmentTypeEnum
    };
}


