/**
 * Student-Management-System-API
 * The Student-Management-System-API. <a href=\'http://localhost:3000/api-json\'>JSON</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateDto { 
    /**
     * Role within the application.
     */
    role: UserUpdateDto.RoleEnum;
    matrNr?: number;
    email?: string;
    displayName: string;
}
export namespace UserUpdateDto {
    export type RoleEnum = 'SYSTEM_ADMIN' | 'ADMIN_TOOL' | 'MGMT_ADMIN' | 'USER';
    export const RoleEnum = {
        SystemAdmin: 'SYSTEM_ADMIN' as RoleEnum,
        AdminTool: 'ADMIN_TOOL' as RoleEnum,
        MgmtAdmin: 'MGMT_ADMIN' as RoleEnum,
        User: 'USER' as RoleEnum
    };
}


