server:
    url: "http://localhost:4000"
    port: 3100

db:
    type: "postgres"
    port: 5432
    database: "KlingDb"

jwt:
    expiresIn: 36000

logger:
    levels:
        - log
        - error
        - warn
        - debug
        - verbose
    requests: false
    dbErrors: false
