/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AuthTokenDto {
	accessToken: string;
	username: string;
	smsUserId: string;
	id: number;
	role: AuthTokenDto.RoleEnum;
}
export namespace AuthTokenDto {
	export type RoleEnum = "USER" | "ADMIN";
	export const RoleEnum = {
		USER: "USER" as RoleEnum,
		ADMIN: "ADMIN" as RoleEnum
	};
}
