/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FileDto {
	path: string;
	directoryPath: string;
	name: string;
	content: string;
}
