/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JoinMessage {
	type: JoinMessage.TypeEnum;
	sender: string;
	room?: string;
	username: string;
}
export namespace JoinMessage {
	export type TypeEnum = "JOIN" | "LEAVE" | "CHAT" | "SELECT_FILE";
	export const TypeEnum = {
		JOIN: "JOIN" as TypeEnum,
		LEAVE: "LEAVE" as TypeEnum,
		CHAT: "CHAT" as TypeEnum,
		SELECTFILE: "SELECT_FILE" as TypeEnum
	};
}
