/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3000/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from "./category";
import { CodeTemplate } from "./codeTemplate";
import { Submission } from "./submission";
import { TestCase } from "./testCase";
import { User } from "./user";

export interface Problem {
	id: string;
	title: string;
	difficulty: Problem.DifficultyEnum;
	codeTemplates?: Array<CodeTemplate>;
	testCases?: Array<TestCase>;
	submissions?: Array<Submission>;
	categories: Array<Category>;
	creator?: User;
	creatorId: number;
	creationDate: Date;
}
export namespace Problem {
	export type DifficultyEnum = "EASY" | "MEDIUM" | "HARD";
	export const DifficultyEnum = {
		EASY: "EASY" as DifficultyEnum,
		MEDIUM: "MEDIUM" as DifficultyEnum,
		HARD: "HARD" as DifficultyEnum
	};
}
