/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeTemplateDto } from "./codeTemplateDto";
import { SubmissionDto } from "./submissionDto";
import { TestCaseDto } from "./testCaseDto";
import { UserDto } from "./userDto";

export interface ProblemDto {
	/**
	 * Unique Id of this problem.
	 */
	id: string;
	/**
	 * Title of this problem.
	 */
	title: string;
	/**
	 * Categories of this problem.
	 */
	categories: Array<string>;
	/**
	 * The difficulty of this problem.
	 */
	difficulty: ProblemDto.DifficultyEnum;
	creationDate?: Date;
	creatorId: number;
	creator?: UserDto;
	status?: ProblemDto.StatusEnum;
	submissions?: Array<SubmissionDto>;
	/**
	 * Contains code templates that should be modified/extended by students.
	 */
	codeTemplates?: Array<CodeTemplateDto>;
	testCases?: Array<TestCaseDto>;
}
export namespace ProblemDto {
	export type DifficultyEnum = "EASY" | "MEDIUM" | "HARD";
	export const DifficultyEnum = {
		EASY: "EASY" as DifficultyEnum,
		MEDIUM: "MEDIUM" as DifficultyEnum,
		HARD: "HARD" as DifficultyEnum
	};
	export type StatusEnum = "ATTEMPTED" | "SOLVED" | "UNSOLVED";
	export const StatusEnum = {
		ATTEMPTED: "ATTEMPTED" as StatusEnum,
		SOLVED: "SOLVED" as StatusEnum,
		UNSOLVED: "UNSOLVED" as StatusEnum
	};
}
