/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDto } from "./fileDto";

export interface SolutionDto {
	id?: number;
	name?: string;
	userId: number;
	files: Array<FileDto>;
	language: string;
}
