/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Evaluation } from "./evaluation";
import { ProblemDao } from "./problemDao";
import { SolutionDao } from "./solutionDao";
import { SubmissionTag } from "./submissionTag";
import { User } from "./user";

export interface Submission {
	id: number;
	problem: ProblemDao;
	problemId: string;
	user?: User;
	userId: number;
	solution?: SolutionDao;
	solutionId: number;
	evaluation?: Evaluation;
	evaluationId: number;
	tags?: Array<SubmissionTag>;
}
