/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProblemDao } from "./problemDao";

export interface TestCase {
	id: number;
	problem?: ProblemDao;
	problemId: string;
	input: any;
	expected?: any;
}
