/**
 * Kling-API
 * The Kling-API. <a href='http://localhost:3100/api-json'>JSON</a>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Permission } from "./permission";
import { Submission } from "./submission";

export interface User {
	id: number;
	smsUserId: string;
	username: string;
	role: User.RoleEnum;
	permissions?: Array<Permission>;
	submissions?: Array<Submission>;
}
export namespace User {
	export type RoleEnum = "USER" | "ADMIN";
	export const RoleEnum = {
		USER: "USER" as RoleEnum,
		ADMIN: "ADMIN" as RoleEnum
	};
}
