version: '3.8'

services:
  review-service:
    build: ./
    container_name: review-service
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    command: npm run start:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
      - /usr/src/app/node_modules
